/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package aestrella;

/**
 *
 * @author Marc
 */
public class Estaciones {

    static public String [] listadoEstaciones = {"Aeroport",
"Alameda",
"Albalat dels Sorells",
"Alberic",
"Alboraya-Palmaret",
"Alboraya-Peris Arago",
"Alfauir",
"Alginet",
"Almassera",
"Amistat",
"Aragon",
"Ausias March",
"Av. del Cid",
"Ayora",
"Àngel Guimera",
"Bailen",
"Betera",
"Benaguasil 1r",
"Benaguasil 2n",
"Benicalap",
"Beniferri",
"Benimaclet",
"Benimamet",
"Benimodo",
"Burjassot",
"Burjassot - Godella",
"Campament",
"Campanar - La Fe",
"Campus de Burjassot",
"Cantereria",
"Carlet",
"Colon",
"Col·legi El Vedat",
"Dr. Lluch",
"El Clot",
"Empalme",
"Entrepins",
"Espioca",
"Estadi del Llevant",
"Eugenia Viñes",
"Facultats",
"Faitanar",
"Fira Valencia",
"Florista",
"Foios",
"Font Almaguer",
"Francisco Cubells",
"Fuente del Jarro",
"Garbi",
"Godella",
"Grau - Canyamelar",
"Joaquin Sorolla",
"L'Alcudia",
"L'Eliana",
"La Cadena",
"La Canyada",
"La Carrasca",
"La Coma",
"La Granja",
"La Marina",
"La Pobla de Farnals",
"La Pobla de Vallbona",
"La Vallesa",
"Les Arenes",
"Les Carolines/Fira",
"Ll. Llarga - Terramelar",
"Lliria",
"Machado",
"Manises",
"Maritim - Serreria",
"Marxalenes",
"Mas del Rosari",
"Masies",
"Massalaves",
"Massamagrell",
"Massarrojos",
"Mediterrani",
"Meliana",
"Mislata",
"Mislata - Almassil",
"Moncada - Alfara",
"Montesol",
"Montortal",
"Museros",
"Neptu",
"Nou d'Octubre",
"Omet",
"Orriols",
"Paiporta",
"Palau de Congressos",
"Paterna",
"Patraix",
"Picanya",
"Picassent",
"Pl. Espanya",
"Pont de Fusta",
"Primado Reig",
"Quart de Poblet",
"Rafelbunyol",
"Realon",
"Reus",
"Rocafort",
"Rosas",
"S. Psiquiatric",
"Safranar",
"Sagunt",
"Salt de l'Aigua",
"Sant Isidre",
"Sant Joan",
"Sant Miquel dels Reis",
"Sant Ramon",
"Santa Gemma - Parc Cientific UV",
"Santa Rita",
"Seminari - CEU",
"Serreria",
"Tarongers",
"Turia",
"Tomas y Valiente",
"Torre del Virrey",
"Torrent",
"Torrent Avinguda",
"Tossal del Rei",
"Transits",
"TVV",
"Universitat Politecnica",
"V. Andres Estelles",
"V. Zaragoza",
"Valencia Sud",
"Villanueva de Castellon",
"Xativa"};
    
}
